### PR TITLE
EC2 PVM boot fix

### PR DESCRIPTION
**Pull request by qrntz**
The resulting AMI gives off bogus error messages on boot I couldn't find a way to avoid:

```
"main" "root=/dev/sda" "ro" "4"
vbd 2048 is hd0
******************* BLKFRONT for device/vbd/2048 **********
backend at /local/domain/0/backend/vbd/2737/2048
Failed to read /local/domain/0/backend/vbd/2737/2048/feature-barrier.
Failed to read /local/domain/0/backend/vbd/2737/2048/feature-flush-cache.
20971520 sectors of 512 bytes
**************************
vbd 2051 is hd1
******************* BLKFRONT for device/vbd/2051 **********
backend at /local/domain/0/backend/vbd/2737/2051
Failed to read /local/domain/0/backend/vbd/2737/2051/feature-barrier.
Failed to read /local/domain/0/backend/vbd/2737/2051/feature-flush-cache.
1835008 sectors of 512 bytes
**************************
vbd 2064 is hd2
******************* BLKFRONT for device/vbd/2064 **********
backend at /local/domain/0/backend/vbd/2737/2064
Failed to read /local/domain/0/backend/vbd/2737/2064/feature-barrier.
Failed to read /local/domain/0/backend/vbd/2737/2064/feature-flush-cache.
312705024 sectors of 512 bytes
**************************
Booting '3.16.0-4-amd64'
root (hd0,1)
Filesystem type is ext2fs, partition type 0x83
kernel /boot/vmlinuz-3.16.0-4-amd64 root=/dev/xvda2 ro
initrd /boot/initrd.img-3.16.0-4-amd64
============= Init TPM Front ================
Tpmfront:Error Unable to read device/vtpm/0/backend-id during tpmfront initialization! error = E
NOENT
Tpmfront:Info Shutting down tpmfront
close blk: backend=/local/domain/0/backend/vbd/2737/2048 node=device/vbd/2048
close blk: backend=/local/domain/0/backend/vbd/2737/2051 node=device/vbd/2051
close blk: backend=/local/domain/0/backend/vbd/2737/2064 node=device/vbd/2064
```

Boots fine though.

### CODE REVIEW

**Comment by JedMeister** [comment]
Thanks @qrntz 

So long as it works, having some bogus errors during boot is not a big deal IMO. :smile:

**Comment by qrntz** [comment]
Thought so too. :shipit:

**Comment by alonswartz** [comment]
- Has this been tested on other instance sizes?
- Does the instance still get /dev/xvdX? I.e. [pvmshim/overlay/etc/grub.d/40_custom](https://github.com/turnkeylinux/buildtasks/blob/master/patches/ec2-pvmshim/overlay/etc/grub.d/40_custom)

**Comment by alonswartz** [comment]
I see there are 2 main changes: using different AKI's, and setting /dev/sdX instead of /dev/xvdX.
- Are both changes required to fix the issue?
- When you confirmed the issue, did you test all regions?

**Comment by alonswartz** [comment]
Does the fix still work if you change the rootfs volume size via the aws ux?

**Comment by qrntz** [comment]
> Has this been tested on other instance sizes?

Yes, I've tested all of the [previous generation](https://aws.amazon.com/ec2/previous-generation/) and all of the general-purpose (t2, m4, m3) [current generation](https://aws.amazon.com/ec2/instance-types/) instances.

> Does the instance still get /dev/xvdX? I.e. pvmshim/overlay/etc/grub.d/40_custom 

Yes, the devices are renamed to /dev/xvdX by the kernel.

> Are both changes required to fix the issue?

Yes, in my experience. hd00 because of the partitioned root volume, and using /dev/sdX for PVM is the actual fix.

> When you confirmed the issue, did you test all regions? (update: the actual problem, not the fix)

Jeremy said he has checked different regions and AMIs to confirm the issue. I checked different sizes, AMIs and regions after applying the fix — no issues.

> Does the fix still work if you change the rootfs volume size via the aws ux?

Yes.

**Pull request merged**
